# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  encoding: utf-8
  username: wikipin
  password: <%= ENV["password_pg"]%>
  pool: 5
  timeout: 5000
  su_username: postgres_su        # a superuser for the database
  su_password:                    # the superuser's password

development:
  <<: *default
  adapter: postgis
  database: wikipin_db_dev
  postgis_extension: postgis               # default is postgis
  schema_search_path: public,postgis

test:
  adapter: postgis
  <<: *default
  database: wikipin_db_test

production:
  <<: *default
  database: wikipin_production
